bookmark/urls.py
from django.urls import path
import bookmark.views
from .views import *
urlpatterns = [
    # path('', bookmark.views.bookmark_category, name='bookmark_category'),
    # path('<int:book_category_id>/bookmark_list/', 
    #      bookmark.views.bookmark_list, name='bookmark_list'),
    # path('bookmark_update/<int:pk>/',
    #      BookmarkUpdate.as_view(), name='bookmark_update'),
    # path('bookmark_delete/<int:pk>/',
    #      BookmarkDelete.as_view(), name='bookmark_delete'),
    # path('bookmark_create/', BookmarkCreate.as_view(), name='bookmark_create'),
    # path('bookmark_detail/<int:pk>/',
    #      BookmarkDetail.as_view(), name='bookmark_detail'),

    path('', bookmark.views.bookmark_category,
         name='bookmark_category'),  # 북마크 메인
    path('<int:book_category_id>/bookmark_list/', bookmark.views.bookmark_list,
         name='bookmark_list'),  # 북마크 리스트
    path('bookmark_create/', BookmarkCreate.as_view(),
         name='bookmark_create'),  # url 추가 확인
    path('bookmark_detail/<int:pk>/', BookmarkDetail.as_view(),
         name='bookmark_detail'),  # 북마크 추가
    path('bookmark_update/<int:pk>/', BookmarkUpdate.as_view(),
         name='bookmark_update'),  # 북마크 수정
    path('bookmark_delete/<int:pk>/', BookmarkDelete.as_view(),
         name='bookmark_delete'),  # 북마크 삭제 확인

]

jamjamproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import jamjamapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', jamjamapp.views.login, name='login'),  # 로그인(첫화면)
    path('main/', jamjamapp.views.main, name='main'),  # 메인
    path('layout/', jamjamapp.views.layout, name='layout'),  # 백메인
    path('calendar/', jamjamapp.views.calendar_view, name="calendar"),#일정
    path('event/new/', jamjamapp.views.event, name="new"),#일정 생성
    path('event/edit/<int:event_id>', jamjamapp.views.event, name="edit"),#일정 수정
    path('community/', jamjamapp.views.community, name='community'),  # 커뮤니티 메인
    path('course/', jamjamapp.views.course, name='course'),  # 코스 메인
    path('course_detail/', jamjamapp.views.course_detail, name='course_detail'),  # 코스 디테일
    path('shop/', jamjamapp.views.shop, name='shop'),  # 샵 메인
    path('theme/', jamjamapp.views.theme, name='theme'),  # 폰트/배경 샵
    path('option/', jamjamapp.views.option, name='option'),  # 기능 샵
    path('jampay/', jamjamapp.views.jampay, name='jampay'),  # 잼 구매 샵
    path('mypage/', jamjamapp.views.mypage, name='mypage'),  # 마이페이지
    path('commu_detail/<str:id>/', jamjamapp.views.commu_detail, name='commu_detail'),  # 커뮤니티 게시글 자세히 보기(프론트)
    path('commu_edit/<str:id>/', jamjamapp.views.commu_edit, name='commu_edit'),
    path('commu_update/<str:id>/', jamjamapp.views.commu_update, name='commu_update'),  # 게시글 수정
    #path('community_search/<int:hashtag_id>/', jamjamapp.views.community, name='community'),  # 게시글 각 카테고리 페이지(해시태그로 치면 search)
    path('commu_write/', jamjamapp.views.commu_write, name='commu_write'),
    path('commu_write/commu_new/', jamjamapp.views.commu_new, name='commu_new'),
    path('commu_delete/<str:id>/', jamjamapp.views.commu_delete, name='commu_delete'),  # 게시글 삭제
    path('commu_like/<int:pk>', jamjamapp.views.commu_like, name='commu_like'),
    path('course_eat/', jamjamapp.views.course_eat,
         name='course_eat'),  # course_eat 전체글 보기
    path('course_eat_detail/<str:id>/', jamjamapp.views.course_eat_detail,
         name='course_eat_detail'),  # eat 게시글 자세히 보기
    path('course_eat_R/<int:small_region_id>/',
         jamjamapp.views.course_eat_R, name='course_eat_R'),  # eat search
    path('course_eat_write/course_eat_C/', jamjamapp.views.course_eat_C,
         name='course_eat_C'),  # eat 게시글 C
    path('course_eat_U/<str:id>/', jamjamapp.views.course_eat_U,
         name='course_eat_U'),  # eat 게시글 수정
    path('course_eat_delete/<str:id>/', jamjamapp.views.course_eat_delete,
         name='course_eat_delete'),  # eat 게시글 삭제
    path('course_eat_like/<int:pk>', jamjamapp.views.course_eat_like,
         name='course_eat_like'),  # eat 게시글 좋아요
    path('course_look/', jamjamapp.views.course_look,
         name='course_look'),  # course_eat 전체글 보기
    path('course_look_detail/<str:id>/', jamjamapp.views.course_look_detail,
         name='course_look_detail'),  # look 게시글 자세히 보기
    path('course_look_R/<int:small_region_id>/',
         jamjamapp.views.course_look_R, name='course_look_R'),  # look search
    path('course_look_write/course_look_C/',
         jamjamapp.views.course_look_C, name='course_look_C'),  # look 게시글 C
    path('course_look_U/<str:id>/', jamjamapp.views.course_look_U,
         name='course_look_U'),  # look 게시글 수정
    path('course_look_delete/<str:id>/', jamjamapp.views.course_look_delete,
         name='course_look_delete'),  # look 게시글 삭제
    path('course_look_like/<int:pk>', jamjamapp.views.course_look_like,
         name='course_look_like'),  # look 게시글 좋아요
    path('course_play/', jamjamapp.views.course_play,
         name='course_play'),  # course_eat 전체글 보기
    path('course_play_detail/<str:id>/', jamjamapp.views.course_play_detail,
         name='course_play_detail'),  # play 커뮤니티 게시글 자세히 보기
    path('course_play_R/<int:small_region_id>/',
         jamjamapp.views.course_play_R, name='course_play_R'),  # play search
    path('course_play_write/course_play_C/',
         jamjamapp.views.course_play_C, name='course_play_C'),  # play 게시글 C
    path('course_play_U/<str:id>/', jamjamapp.views.course_play_U,
         name='course_play_U'),  # play 게시글 수정
    path('course_play_delete/<str:id>/', jamjamapp.views.course_play_delete,
         name='course_play_delete'),  # play 게시글 삭제
    path('course_play_like/<int:pk>', jamjamapp.views.course_play_like,
         name='course_play_like'),  # play 게시글 좋아요
    path('bookmark/', include('bookmark.urls')),#북마크앱 url
    # ------민정 개발-------
    path('pay/', jamjamapp.views.pay, name='pay'),  # 결제 확인
    path('completepay/', jamjamapp.views.completepay, name='completepay'),  # 결제완료
    path('finalpay/', jamjamapp.views.finalpay, name='finalpay'),  # 진짜 결제
    path('day_detail/', jamjamapp.views.day_detail,
         name='day_detail'),  # 데이디테일 페이지
    path('diary/diary_create', jamjamapp.views.diary_create,
         name='diary_create'),  # 데이디테일 작성
    path('bucketlist_write/bucket_create/',
         jamjamapp.views.bucket_create, name='bucket_create'),  # 버킷리스트 작성
    path('diary_detail/<str:id>/', jamjamapp.views.diary_detail,
         name='diary_detail'),  # 데이디테일 디테일 페이지
    path('diary/diary_edit/', jamjamapp.views.diary_edit,
         name='diary_edit'),  # 데이디테일 수정(프론트)
    #     path('diary_edit/<str:id>/', jamjamapp.views.diary_edit,
    #          name='diary_edit'),  # 데이디테일 수정(백)
    path('profile_edit/', jamjamapp.views.profile_edit,
         name='profile_edit'),  # 프로필 수정(프론트)
    path('p_edit/<str:id>/', jamjamapp.views.p_edit, name='p_edit'),  # 프로필 수정(백)
    path('connection', jamjamapp.views.connection, name='connection'),  # 연인 연결
    path('purchaselist', jamjamapp.views.purchaselist,
         name='purchaselist'),  # 구매 목록 확인
    path('purchase_example/', jamjamapp.views.purchase_example,  # 아이템 자세히 보기
         name='purchase_example'),
    path('diary_delete/<str:id>/', jamjamapp.views.diary_delete,
         name='diary_delete'),  # 데이디테일 삭제
    path('profile/', jamjamapp.views.profile, name='profile'),  # 프로필 페이지
    path('bucketlist/', jamjamapp.views.bucketlist,
         name='bucketlist'),  # 버킷리스트 페이지
    path('bucket_edit/<str:id>', jamjamapp.views.bucket_edit,
         name='bucket_edit'),  # 버킷리스트 수정
    path('bucket_delete/<str:id>/', jamjamapp.views.bucket_delete,
         name='bucket_delete'),  # 버킷리스트 삭제
    path('bucket_detail/<str:id>/', jamjamapp.views.bucket_detail,
         name='bucket_detail'),  # 버킷리스트 디테일
    # ------예찬 개발-------
    path('login/', jamjamapp.views.signin, name='signin'),
    path('signup/', jamjamapp.views.signup, name='signup'),
    path('signout/', jamjamapp.views.signout, name='signout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jamjamapp/models.py
from django.db import models
from django.conf import settings
from functools import update_wrapper
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, User
from django.utils import timezone
from django.urls import reverse

# 게시글


class Blog(models.Model):
    Title = models.CharField(max_length=200)
    Writer = models.CharField(max_length=100)
    Write_day = models.DateTimeField('date published')
    Content = models.TextField()
    Image = models.ImageField(upload_to='images/', blank=True)
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    Blog_likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="Blog_likes")
    view_count = models.IntegerField(default=0)

    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_post', blank=True)
    favorite = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='favorite_post', blank=True)

    def __str__(self):
        return self.Title

    class Meta:
        ordering = ['-id']

# 댓글

class Comment(models.Model):
    post_id = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('data published', null = True)
    
    def __str__(self):
        return self.text

# 커뮤니티 카테고리를 해시태그라고 편의상 해둠


class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

# course_eat_C


class Eat_C(models.Model):
    Title = models.CharField(max_length=200)
    Writer = models.CharField(max_length=100)
    Write_day = models.DateTimeField('date published')
    Content = models.TextField()
    Image = models.ImageField(upload_to='images/', blank=True)
    big_region = models.ManyToManyField('big_region', blank=True)
    small_region = models.ManyToManyField('small_region', blank=True)
    Eat_likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="Eat_likes")
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.Title

# course_look_C


class Look_C(models.Model):
    Title = models.CharField(max_length=200)
    Writer = models.CharField(max_length=100)
    Write_day = models.DateTimeField('date published')
    Content = models.TextField()
    Image = models.ImageField(upload_to='images/', blank=True)
    big_region = models.ManyToManyField('big_region', blank=True)
    small_region = models.ManyToManyField('small_region', blank=True)
    Look_likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="Look_likes")
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.Title

# course_play_C


class Play_C(models.Model):
    Title = models.CharField(max_length=200)
    Writer = models.CharField(max_length=100)
    Write_day = models.DateTimeField('date published')
    Content = models.TextField()
    Image = models.ImageField(upload_to='images/', blank=True)
    big_region = models.ManyToManyField('big_region', blank=True)
    small_region = models.ManyToManyField('small_region', blank=True)
    play_likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="Play_likes")
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.Title


class Big_Region(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Small_Region(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

# 스크랩


class Bookmark(models.Model):
    book_site_name = models.CharField(max_length=50)
    book_url = models.URLField()

    def __str__(self):
        return self.book_site_name + " : " + self.book_url

    class Meta:
        ordering = ["book_site_name"]


# 다이어리
class Event(models.Model):
    diary_start_time = models.DateTimeField("시작시간")
    diary_end_time = models.DateTimeField("마감시간")
    diary_title = models.CharField("이벤트 이름", max_length=50)
    diary_description = models.TextField("상세")

    class Meta:
        verbose_name = "이벤트 데이터"
        verbose_name_plural = "이벤트 데이터"

    def __str__(self):
        return self.diary_title

    @property
    def get_html_url(self):
        diary_url = reverse('edit', args=(self.id,))
        return f'<a href="{diary_url}"> {self.diary_title} </a>'


# ----민정이 개발 부분------


class Post(models.Model):
    diary_title = models.CharField(max_length=100)  # 제목
    # 기록하고 싶은 날짜( ex) 여행 다녀온 날 등 )
    diary_date = models.CharField(
        null=False, max_length=15, default='oooo년 oo월 oo일')
    diary_body = models.TextField()  # 내용

    def __str__(self):
        return self.diary_title

# 버킷리스트 모델


class Bucket(models.Model):
    bucket_title = models.CharField(max_length=100)  # 제목
    bucket_date = models.CharField(
        null=False, max_length=15, default='oooo년 oo월 oo일')  # 하고 싶은 날짜( ex) ~날 ~하기 등 )
    bucket_body = models.TextField()  # 내용

    def __str__(self):
        return self.bucket_title

# 프로필 모델


class Profile(models.Model):
    nickname = models.CharField(max_length=20)

    def __str__(self):
        return self.nickname

# ----예찬이 개발 부분------


class UserManager(BaseUserManager):

    use_in_migrations = True

    def create_user(self, email, username, password, **extra_fields):
        if not email:
            raise ValueError('이메일을 입력해주세요')
        if not password:
            raise ValueError('비밀번호를 입력해주세요')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.is_staff = False
        user.is_superuser = False
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class SettingUser(AbstractBaseUser, PermissionsMixin):
    g = [
        (1, '성별'),
        (2, '남성'),
        (3, '여성')
    ]

    objects = UserManager()
    email = models.EmailField(max_length=60, unique=True)
    username = models.CharField(max_length=20, unique=True, null=True)
    nickname = models.CharField(max_length=20, null=True)
    phone_number = models.CharField(default="010", max_length=11, null=True)
    birthyear = models.CharField(max_length=4, null=True)
    birthmonth = models.CharField(max_length=2, null=True)
    birthday = models.CharField(max_length=2, null=True)
    gender = models.IntegerField(default=1, choices=g, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return str(self.username)

bookmark/forms.py
from django import forms
from .models import Book_Category

class Book_CategoryForm(forms.ModelForm):
    class Meta:
        model = Book_Category
        fields = ['name']

class BookmarkAdmin(forms.ModelForm):
    list_display = ['id', 'book_site_name', 'book_url']

bookmark/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import *
from .models import Bookmark, Book_Category
from .forms import Book_CategoryForm
from django.urls import reverse_lazy


def bookmark_category(request, book_category=None):
    books = Bookmark.objects
    book_categorys = Book_Category.objects
    if request.method == 'POST':
        form = Book_CategoryForm(request.POST, instance=book_category)
        if form.is_valid():
            book_category = form.save(commit=False)
            if Book_Category.objects.filter(name=form.cleaned_data['name']):
                form = Book_CategoryForm()
                error_message = "이미 존재하는 해시태그 입니다."
                return render(request, 'bookmark_category.html', {'form': form, "error_message": error_message})
            else:
                book_category.name = form.cleaned_data['name']
                book_category.save()
            return redirect('bookmark_category')
    else:
        form = Book_CategoryForm(instance=book_category)
        return render(request, 'bookmark_category.html', {'books': books, 'book_categorys': book_categorys, 'form': form})


def bookmark_list(request, book_category_id):
    book_category = get_object_or_404(Book_Category, id=book_category_id)
    return render(request, 'bookmark_list.html', {'book_category': book_category})


class BookmarkUpdate(UpdateView):
    model = Bookmark
    fields = ['book_site_name', 'book_url', 'book_category']
    template_name = 'bookmark_update.html'


class BookmarkDelete(DeleteView):
    model = Bookmark
    template_name = 'bookmark_delete.html'
    success_url = reverse_lazy('bookmark_category') # 성공하면 bookmark_category url을 띄우겠다.


class BookmarkCreate(CreateView):
    model = Bookmark
    fields = ['book_site_name', 'book_url', 'book_category']
    template_name = 'bookmark_create.html'

class BookmarkDetail(DetailView):
    model = Bookmark
    template_name = 'bookmark_detail.html'

bookmark/templates/bookmark_category.html
{% extends 'layout1.html' %} 
{% load static %}

{% block head %}
<title>너와 나의 달달한 소스, JamJam</title>

{% endblock %}
{% block contents %}
<link href="{% static 'jamjamapp/css/bookmark.css' %}" rel="stylesheet" />


<div class="bookmark-category-container">
    <div class="category-search">
        <h1>새로운 URL 카테고리 생성하기</h1>
        <p>카테고리를 추가하여 스크랩한 url을 종류별로 구분해보세요</p>
        <form method="POST">
          {% csrf_token %}
          <br><br>
          <table>
              {{form.as_table}}{{ error_message }}
          </table>
          <br>
          <input class="category-enroll-btn" type="submit" value="제출하기">
       </form>
    </div>


    <div class="categorylist">

        <h2>[ 카테고리 목록 ]</h2>
            {% for book_categorys in book_categorys.all %}
            <a href="{% url 'bookmark_list' book_categorys.id %}">{{ book_categorys.name }}</a><br>
            {% endfor %}    
    </div>
</div>
{% endblock %}

bookmark/templates/bookmark_create.html
{% extends 'layout1.html' %} 
{% load static %}

{% block head %}
<title>너와 나의 달달한 소스, JamJam</title>

{% endblock %}
{% block contents %}
<link href="{% static 'jamjamapp/css/bookmark.css' %}" rel="stylesheet" />


<div class="bookmark-create-container">
    <div class="bookmark-create-head">
        <h1>새로운 URL 추가하기</h1>
    </div>
    <p>전으로 돌아가 해당 페이지의 url을 복사하여 Book url에 입력해주시고,<br><br>
        Book site name으로 북마크 이름을,<br><br>
        Book category로 북마크의 카테고리도 설정해보세요!</p>
        <br>
        <h1>↓</h1>
        <br>
    <form action="" method = "post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="추가완료">
    </form>
</div>
<br><br><br><br><br><br><br>
{% endblock %}

bookmark/templates/bookmark_delete.html
{% extends 'layout1.html' %} 
{% load static %}

{% block head %}
<title>너와 나의 달달한 소스, JamJam</title>

{% endblock %}
{% block contents %}
<link href="{% static 'jamjamapp/css/bookmark.css' %}" rel="stylesheet" />


<div class="bookmark-detail-container">
    <div class="bookmark-detail-head">
        <h1>북마크를 삭제하시겠습니까?</h1>
    </div>
    <span>Do you want to delete {{object}}?</span>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제완료">
    </form>
</div>
{% endblock %}

bookmark/templates/bookmark_detail.html
{% extends 'layout1.html' %} 
{% load static %}

{% block head %}
<title>너와 나의 달달한 소스, JamJam</title>

{% endblock %}
{% block contents %}
<link href="{% static 'jamjamapp/css/bookmark.css' %}" rel="stylesheet" />

{{object.book_site_name}}<br>
{{object.book_url}}<br>
<a href="{% url 'bookmark_category' %}">북마크 홈으로</a>
{% endblock %}

bookmark/templates/bookmark_list.html
{% extends 'layout1.html' %} 
{% load static %}

{% block head %}
<title>너와 나의 달달한 소스, JamJam</title>

{% endblock %}
{% block contents %}
<link href="{% static 'jamjamapp/css/bookmark.css' %}" rel="stylesheet" />


<div class="bookmark-list-container">
    <h1>"{{ book_category }}" 카테고리 목록</h1>
    
    <div class="bookmark-create-btn">
        <button class="create-btn">
            <a href="{% url 'bookmark_create' %}" style="text-decoration:none; text-align:center; content-align:center; font-size:30px;">URL 추가</a>
        </button>
    </div>
    <br><br><br><br>
    <table class="list-table">
        <thead>
            <tr>
                <th>제목</th>
                <th>수정</th>
                <th>삭제</th>
            </tr>
        </thead>
            {% for bookmark in book_category.bookmark_set.all %}
            <tbody>
                <td><a href="{{bookmark.book_url}}">{{bookmark.book_site_name}}</a></td>
                <td><a href="{% url 'bookmark_update' bookmark.id %}">수정</a></td>
                <td><a href="{% url 'bookmark_delete' bookmark.id %}">삭제</a></td><br>
            </tbody>
            {% endfor %}
    </table>
</div>
{% endblock %}

bookmark/templates/bookmark_update.html
{% extends 'layout1.html' %} 
{% load static %}

{% block head %}
<title>너와 나의 달달한 소스, JamJam</title>

{% endblock %}
{% block contents %}
<link href="{% static 'jamjamapp/css/bookmark.css' %}" rel="stylesheet" />


<div class="bookmark-create-container">
    <div class="bookmark-create-head">
        <h1>수정하기</h1>
    </div>
    <form action="" method = "post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="수정완료">
    </form>
</div>
{% endblock %}